### ISSUE TITLE
Adding variables and dates to requests isn't filtering the data

### ISSUE THREAD

**Issue by mark-ergoflex** [urbanobservatory/uo-api-v1.1#11]
When making a request like http://newcastle.urbanobservatory.ac.uk/api/v1.1/sensors/PER_AIRMON_MESH1971150/data/json/?starttime=20211115000000&endtime=20211115235959&sensor_type=NO2 I would expect only NO2 data for one day to be returned. This was the case until recently. 

At the moment, the above request returns all data from the 1st of the month up to the time the request is made and for all the different sensor types, making for unexpectedly large responses.

**Comment by nharris172** [comment]
Hi Mark. 

adding sensor_type just filters the sensors so you are getting data from all variable for all sensors that record NO2. This i'll admit is very confusing. but if you add data_variable=NO2 you'll only get NO2. 


https://newcastle.urbanobservatory.ac.uk/api/v1.1/sensors/PER_AIRMON_MESH1971150/data/json/?starttime=20211115000000&endtime=20211115235959&sensor_type=NO2&data_variable=NO2

**Comment by mark-ergoflex** [comment]
Thanks Neil. 

I had mis-understood the data variable parameter and that does cut down the amount of data received quite a bit. 

The start and end times don't seem to have any affect though. Using the examples above I'd expect only values from 15th November but the returned timestamps range from the 1st to the 17th.

**Comment by nharris172** [comment]
Good point something odd is happening there with the timestamps. I'll have a dig

**Comment by nharris172** [comment]
this should now be fixed. thanks for flagging this error

**Comment by mark-ergoflex** [comment]
That's great, thanks.
