### ISSUE TITLE
Sensor data query not returning

### ISSUE THREAD

**Issue by benwatson528** [urbanobservatory/uo-api-v1.1#7]
Hello, I'm enjoying using this API, there's some great data in it. I'm trying to query for the most recent 10 `NO` sensor data records and I'm not having much luck - I stopped it after about 15 minutes with no data returned.

The query:
```
http://uoweb3.ncl.ac.uk/api/v1.1/sensors/data/json/?sensor_type=NO&last_n_records=10
```

I've tried various combinations of `starttime`, `endtime`, `last_n_records`, `last_n_days`, but they all just run continuously. Is there another way I should be formulating the query to get it to return more quickly? I'm worried that I'm triggering a full-table scan.

Thanks,

Ben

**Comment by nharris172** [comment]
Hi Ben

there seems to be a bug with the `last_n_records` tag I'm looking into it.

could you try using `uoweb3.ncl.ac.uk/api/v1.1/sensors/data/json/?data_variable=NO&last_n_days=1` for the time being?

**Comment by benwatson528** [comment]
Thanks Neil, that gives me what I need.

Ben
